# Generated by Django 5.2.3 on 2025-10-26 21:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('isin', models.CharField(blank=True, help_text='International Securities Identification Number (ISIN)', max_length=12, null=True, unique=True)),
                ('instrument_type', models.CharField(blank=True, choices=[('CFD', 'CFD'), ('ETF', 'ETF'), ('ETC', 'ETC'), ('STOCK', 'Stock')], max_length=20, null=True)),
                ('currency', models.CharField(blank=True, help_text='Currency of the instrument (e.g. USD, EUR)', max_length=3, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('logo_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('xtb_id', models.CharField(max_length=50, unique=True)),
                ('time', models.DateTimeField()),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('account_type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'CashOperations',
                'ordering': ['-time'],
                'indexes': [models.Index(fields=['account_type', 'time'], name='investments_account_b3d7da_idx')],
            },
        ),
        migrations.CreateModel(
            name='OverviewWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('row', models.PositiveIntegerField(default=1)),
                ('column', models.PositiveIntegerField(default=1)),
                ('width_units', models.PositiveIntegerField(default=1)),
                ('height_units', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_widgets', to='investments.dashboard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('account_type', models.CharField(max_length=10)),
                ('open_time', models.DateTimeField()),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('market_price', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField()),
                ('purchase_value', models.FloatField()),
                ('gross_pl', models.FloatField(verbose_name='Gross P/L')),
                ('gross_pl_perc', models.FloatField(blank=True, null=True)),
                ('swap', models.FloatField(default=0.0)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('position_id', models.CharField(blank=True, max_length=100, null=True)),
                ('instrument_type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Positions',
                'ordering': ['-open_time'],
                'indexes': [models.Index(fields=['symbol', 'account_type', 'status'], name='investments_symbol_d8b967_idx')],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.PositiveIntegerField(default=1)),
                ('column', models.PositiveIntegerField(default=1)),
                ('width_units', models.PositiveIntegerField(default=1)),
                ('height_units', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='investments.dashboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
