# Generated by Django 5.2.3 on 2025-10-27 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overviewwidget',
            name='column',
        ),
        migrations.RemoveField(
            model_name='overviewwidget',
            name='height_units',
        ),
        migrations.RemoveField(
            model_name='overviewwidget',
            name='row',
        ),
        migrations.RemoveField(
            model_name='overviewwidget',
            name='width_units',
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_object_id', models.UUIDField()),
                ('row', models.PositiveIntegerField(default=1)),
                ('column', models.PositiveIntegerField(default=1)),
                ('width_units', models.PositiveIntegerField(default=1)),
                ('height_units', models.PositiveIntegerField(default=1)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='investments.dashboard')),
                ('widget_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'unique_together': {('dashboard', 'widget_content_type', 'widget_object_id')},
            },
        ),
    ]
