# Generated by Django 5.2.3 on 2025-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_chartwidget_remove_overviewwidget_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='overviewwidget',
            name='widget_type',
            field=models.CharField(default='overview', max_length=50),
        ),
    ]
