# Generated by Django 5.2.3 on 2025-11-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(default='main', max_length=10),
            preserve_default=False,
        ),
    ]
