# Generated by Django 5.2.3 on 2025-11-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartwidget',
            name='chart_subtype',
            field=models.CharField(choices=[('timeseries', 'Time Series'), ('pie', 'Pie Chart'), ('sunburst', 'Sunburst'), ('pareto', 'Pareto'), ('bar', 'Bar Chart')], default='timeseries', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
