# Generated by Django 5.2.3 on 2025-11-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_chartwidget_chart_subtype_alter_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartwidget',
            name='variant',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
