# Generated by Django 5.2.3 on 2025-11-16 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_chartwidget_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ChartWidget',
        ),
        migrations.DeleteModel(
            name='OverviewWidget',
        ),
    ]
