# Generated by Django 5.2.3 on 2025-11-16 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_basewidget_delete_chartwidget_delete_overviewwidget'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dashboardwidget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='widget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.basewidget'),
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='widget_content_type',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='widget_object_id',
        ),
    ]
