# Generated by Django 5.2.3 on 2025-11-16 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_alter_dashboardwidget_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
