# Generated by Django 5.2.3 on 2025-11-16 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_delete_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartWidget',
            fields=[
                ('basewidget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.basewidget')),
                ('chart_subtype', models.CharField(choices=[('timeseries', 'Time Series'), ('pie', 'Pie Chart'), ('sunburst', 'Sunburst'), ('pareto', 'Pareto'), ('bar', 'Bar Chart')], max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('investments.basewidget',),
        ),
        migrations.CreateModel(
            name='OverviewWidget',
            fields=[
                ('basewidget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.basewidget')),
            ],
            options={
                'abstract': False,
            },
            bases=('investments.basewidget',),
        ),
    ]
