# Generated by Django 5.2.3 on 2025-11-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_chartwidget_overviewwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableWidget',
            fields=[
                ('basewidget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='investments.basewidget')),
            ],
            options={
                'abstract': False,
            },
            bases=('investments.basewidget',),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
