# Generated by Django 5.2.3 on 2025-11-30 20:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_tablewidget_alter_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp_out', models.DateTimeField()),
                ('timestamp_in', models.DateTimeField()),
                ('amount_out', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency_out', models.CharField(max_length=10)),
                ('account_out', models.CharField(max_length=50)),
                ('xtb_id_out', models.BigIntegerField()),
                ('amount_in', models.DecimalField(decimal_places=6, max_digits=20)),
                ('currency_in', models.CharField(max_length=10)),
                ('account_in', models.CharField(max_length=50)),
                ('xtb_id_in', models.BigIntegerField()),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'TransferOperations',
                'ordering': ['-timestamp_in'],
                'indexes': [models.Index(fields=['currency_out', 'timestamp_in'], name='investments_currenc_43ed1d_idx')],
            },
        ),
    ]
