# Generated by Django 5.2.3 on 2025-11-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_transferoperation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferoperation',
            name='amount_in',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transferoperation',
            name='amount_out',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transferoperation',
            name='exchange_rate',
            field=models.FloatField(),
        ),
    ]
