# Generated by Django 5.2.3 on 2026-02-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_alter_transferoperation_amount_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartwidget',
            name='variant',
        ),
        migrations.AddField(
            model_name='basewidget',
            name='column',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basewidget',
            name='dashboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='investments.dashboard'),
        ),
        migrations.AddField(
            model_name='basewidget',
            name='height_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basewidget',
            name='row',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='basewidget',
            name='width_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='DashboardWidget',
        ),
    ]
