# Generated by Django 5.2.3 on 2026-02-14 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_remove_chartwidget_variant_basewidget_column_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basewidget',
            name='data',
        ),
    ]
