# Generated by Django 5.2.3 on 2026-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0017_remove_basewidget_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='grid_columns',
            field=models.PositiveIntegerField(default=32),
        ),
    ]
