# Generated by Django 5.2.3 on 2026-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0018_dashboard_grid_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='max_width_px',
            field=models.PositiveIntegerField(default=1400),
        ),
    ]
