# Generated by Django 5.2.3 on 2026-04-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0019_dashboard_max_width_px'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
