# Generated by Django 5.2.3 on 2026-04-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0020_dashboard_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
