# Generated by Django 5.2.3 on 2026-05-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basewidget',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
