# Generated by Django 5.2.3 on 2026-05-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_basewidget_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='basewidget',
            name='subtype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
