# Generated by Django 5.2.3 on 2026-05-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_basewidget_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='basewidget',
            name='state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
