# Generated by Django 4.2.2 on 2023-06-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(blank=True, choices=[('INNER', 'INNER'), ('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['main_category', 'subcategory'],
            },
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MainCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MoneyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'MoneyAccounts',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'SubCategories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origin', models.CharField(choices=[('ING', 'ING'), ('PKO', 'PKO'), ('CASH', 'CASH'), ('OUT', 'OUT')], max_length=255)),
                ('destination', models.CharField(choices=[('ING', 'ING'), ('PKO', 'PKO'), ('CASH', 'CASH'), ('OUT', 'OUT')], max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, choices=[('INNER', 'INNER'), ('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.category')),
            ],
            options={
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.maincategory'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.subcategory'),
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_before', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('budget_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.transaction')),
                ('money_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.moneyaccount')),
            ],
            options={
                'verbose_name_plural': 'BalanceHistories',
                'ordering': ['-budget_entry__date', '-budget_entry__updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('main_category', 'subcategory')},
        ),
    ]
