# Generated by Django 4.2.2 on 2023-06-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ['-budget_entry__date', '-budget_entry__updated_at', '-id'], 'verbose_name_plural': 'BalanceHistories'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-updated_at', '-id'], 'verbose_name_plural': 'Transactions'},
        ),
    ]
