# Generated by Django 4.2.2 on 2024-03-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_balancehistory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainCategory',
            new_name='ParentCategory',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent_category', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='parentcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'ParentCategories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='main_category',
            new_name='parent_category',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='defaultname', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(choices=[('INNER', 'INNER'), ('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], default='defaulttype', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent_category', 'name')},
        ),
        migrations.RemoveField(
            model_name='category',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
