# Generated by Django 4.2.2 on 2023-06-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_moneyaccount_alter_budgetexpenseentry_destination_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneyaccount',
            options={'verbose_name_plural': 'MoneyAccounts'},
        ),
    ]
