# Generated by Django 4.2.2 on 2023-06-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_alter_moneyaccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpenseentry',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('INNER', 'INNER'), ('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], max_length=255, null=True),
        ),
    ]
