# Generated by Django 5.2.3 on 2025-07-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_transaction_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCategorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('parent_category_name', models.CharField(max_length=255)),
                ('category_name', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('INNER', 'INNER'), ('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'MonthlyCategorySummaries',
                'ordering': ['parent_category_name', 'category_name', 'year', 'month'],
                'unique_together': {('year', 'month', 'parent_category_name', 'category_name', 'transaction_type')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyParentCategorySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('parent_category_name', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('INNER', 'INNER'), ('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'MonthlyParentCategorySummaries',
                'ordering': ['transaction_type', 'parent_category_name', 'year', 'month'],
                'unique_together': {('year', 'month', 'parent_category_name', 'transaction_type')},
            },
        ),
        migrations.CreateModel(
            name='MonthlySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_savings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ending_balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'MonthlySummaries',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
