# Generated by Django 5.2.3 on 2026-04-29 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_monthlycategorysummary_monthlyparentcategorysummary_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at', '-id'], 'verbose_name_plural': 'Transactions'},
        ),
    ]
