# Generated by Django 4.2.2 on 2023-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_maincategory_name_alter_moneyaccount_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('INNER', 'INNER'), ('INCOMING', 'INCOMING'), ('OUTGOING', 'OUTGOING')], max_length=255, null=True),
        ),
    ]
