# Generated by Django 4.2.2 on 2023-06-09 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_category_transaction_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['main_category', 'subcategory'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'MainCategories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'SubCategories'},
        ),
    ]
