# Generated by Django 4.2.2 on 2023-06-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_alter_category_options_alter_maincategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyaccount',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
