# Generated by Django 4.2.2 on 2023-06-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_moneyaccount_starting_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpenseentry',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
