# Generated by Django 4.2.2 on 2023-06-16 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_budgetexpenseentry_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('money_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.moneyaccount')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
