# Generated by Django 4.2.2 on 2023-06-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_balancehistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'BalanceHistories'},
        ),
    ]
