# Generated by Django 4.2.2 on 2023-06-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_alter_balancehistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetexpenseentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
