# Generated by Django 4.2.2 on 2023-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_budgetexpenseentry_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetexpenseentry',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='budgetexpenseentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
