# Generated by Django 4.2.2 on 2023-06-17 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_rename_timestamp_budgetexpenseentry_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'BalanceHistories'},
        ),
        migrations.RenameField(
            model_name='balancehistory',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
