# Generated by Django 4.2.2 on 2023-06-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_alter_balancehistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='budget_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.budgetexpenseentry'),
        ),
    ]
