# Generated by Django 4.2.2 on 2023-06-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_alter_balancehistory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancehistory',
            name='budget_entry',
        ),
        migrations.AddField(
            model_name='budgetexpenseentry',
            name='balance_history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.balancehistory'),
        ),
    ]
