# Generated by Django 4.2.2 on 2023-06-17 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_remove_balancehistory_budget_entry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetexpenseentry',
            name='balance_history',
        ),
        migrations.AddField(
            model_name='balancehistory',
            name='budget_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.budgetexpenseentry'),
        ),
    ]
