# Generated by Django 4.2.2 on 2023-06-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0020_alter_balancehistory_budget_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'BalanceHistories'},
        ),
    ]
