# Generated by Django 4.2.2 on 2023-06-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_alter_balancehistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancehistory',
            options={'ordering': ['-created_at', '-id'], 'verbose_name_plural': 'BalanceHistories'},
        ),
        migrations.AlterModelOptions(
            name='budgetexpenseentry',
            options={'ordering': ['-created_at', '-id'], 'verbose_name_plural': 'BudgetEntries'},
        ),
    ]
