# Generated by Django 4.2.2 on 2023-06-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0022_alter_balancehistory_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BudgetExpenseEntry',
            new_name='Transaction',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name_plural': 'Transactions'},
        ),
    ]
